services:
  - type: web
    name: online-remult-tutorial
    runtime: static
    buildCommand: npm install; npm build
    staticPublishPath: ./dist
    #  envVars:
    #   - fromGroup: online-remult-tutorial
